/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppAuthScreen {
    'subScreen': 'sign-in' | 'sign-up';
  }
  interface AppHome {}
  interface AppProfile {
    'name': string;
  }
  interface AppRoot {}
  interface AppSignInForm {}
  interface AppSignUpForm {}
}

declare global {


  interface HTMLAppAuthScreenElement extends Components.AppAuthScreen, HTMLStencilElement {}
  var HTMLAppAuthScreenElement: {
    prototype: HTMLAppAuthScreenElement;
    new (): HTMLAppAuthScreenElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSignInFormElement extends Components.AppSignInForm, HTMLStencilElement {}
  var HTMLAppSignInFormElement: {
    prototype: HTMLAppSignInFormElement;
    new (): HTMLAppSignInFormElement;
  };

  interface HTMLAppSignUpFormElement extends Components.AppSignUpForm, HTMLStencilElement {}
  var HTMLAppSignUpFormElement: {
    prototype: HTMLAppSignUpFormElement;
    new (): HTMLAppSignUpFormElement;
  };
  interface HTMLElementTagNameMap {
    'app-auth-screen': HTMLAppAuthScreenElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-sign-in-form': HTMLAppSignInFormElement;
    'app-sign-up-form': HTMLAppSignUpFormElement;
  }
}

declare namespace LocalJSX {
  interface AppAuthScreen extends JSXBase.HTMLAttributes<HTMLAppAuthScreenElement> {
    'subScreen'?: 'sign-in' | 'sign-up';
  }
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'name'?: string;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface AppSignInForm extends JSXBase.HTMLAttributes<HTMLAppSignInFormElement> {}
  interface AppSignUpForm extends JSXBase.HTMLAttributes<HTMLAppSignUpFormElement> {}

  interface IntrinsicElements {
    'app-auth-screen': AppAuthScreen;
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'app-sign-in-form': AppSignInForm;
    'app-sign-up-form': AppSignUpForm;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


