/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import 'stencil-apollo';


export namespace Components {

  interface AppAuthScreen {
    'subScreen': 'sign-in' | 'sign-up';
  }
  interface AppAuthScreenAttributes extends StencilHTMLAttributes {
    'subScreen'?: 'sign-in' | 'sign-up';
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'name': string;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppSignInForm {}
  interface AppSignInFormAttributes extends StencilHTMLAttributes {}

  interface AppSignUpForm {}
  interface AppSignUpFormAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppAuthScreen': Components.AppAuthScreen;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'AppSignInForm': Components.AppSignInForm;
    'AppSignUpForm': Components.AppSignUpForm;
  }

  interface StencilIntrinsicElements {
    'app-auth-screen': Components.AppAuthScreenAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'app-sign-in-form': Components.AppSignInFormAttributes;
    'app-sign-up-form': Components.AppSignUpFormAttributes;
  }


  interface HTMLAppAuthScreenElement extends Components.AppAuthScreen, HTMLStencilElement {}
  var HTMLAppAuthScreenElement: {
    prototype: HTMLAppAuthScreenElement;
    new (): HTMLAppAuthScreenElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSignInFormElement extends Components.AppSignInForm, HTMLStencilElement {}
  var HTMLAppSignInFormElement: {
    prototype: HTMLAppSignInFormElement;
    new (): HTMLAppSignInFormElement;
  };

  interface HTMLAppSignUpFormElement extends Components.AppSignUpForm, HTMLStencilElement {}
  var HTMLAppSignUpFormElement: {
    prototype: HTMLAppSignUpFormElement;
    new (): HTMLAppSignUpFormElement;
  };

  interface HTMLElementTagNameMap {
    'app-auth-screen': HTMLAppAuthScreenElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'app-sign-in-form': HTMLAppSignInFormElement
    'app-sign-up-form': HTMLAppSignUpFormElement
  }

  interface ElementTagNameMap {
    'app-auth-screen': HTMLAppAuthScreenElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-sign-in-form': HTMLAppSignInFormElement;
    'app-sign-up-form': HTMLAppSignUpFormElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
